### ISSUE TITLE
Request header field Content-Type is not allowed by Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by beornborn** [Instabug/web-sdk-sample#7]
Failed to load https://api.instabug.com/api/sdk/v3/features?application_token=token 

Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

It worked 3 days ago

**Comment by ZiadAyman** [comment]
Fixed :) Thanks for reporting it!

**Comment by johnjjung** [comment]
@ZiadAyman I'm still getting this error, is there some sort of configuration that we need to do?

```
Failed to load https://api.instabug.com/api/sdk/v3/features?application_token=: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
17:03:49.261 
```
